# Project environment variables for gryfn
# Context: production
# Scope: any
# Date: Thu, 07 Aug 2025 09:24:14 GMT
# REACT_APP_ELEVENLABS_API_KEY=sk_058f49939b6fc02734b5f91c774b099222f179be6bd71d78


CI=false
NPM_FLAGS=--legacy-peer-deps
REACT_APP_DEEPGRAM_API_KEY=47dab40e4c41b4be66a5871a89f4151332b29be0
REACT_APP_DEEPGRAM_MODEL=nova-3
REACT_APP_DEEPGRAM_URL=https://api.deepgram.com/v1/listen
REACT_APP_SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xeW1weGpwcnd6aG9rdmZqdGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTgyNDIsImV4cCI6MjA3MDEzNDI0Mn0.3jvjE0qmNnSHKCjMyMzBAo7x1t8UVxUpuReATHyeue8
REACT_APP_SUPABASE_URL=https://mqympxjprwzhokvfjthq.supabase.co